# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(852, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.tool_bar = QtWidgets.QToolBar(MainWindow)
        self.tool_bar.setObjectName("tool_bar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tool_bar)
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_clear = QtWidgets.QAction(MainWindow)
        self.action_clear.setObjectName("action_clear")
        self.action_circle = QtWidgets.QAction(MainWindow)
        self.action_circle.setObjectName("action_circle")
        self.action_square = QtWidgets.QAction(MainWindow)
        self.action_square.setObjectName("action_square")
        self.action_triangle = QtWidgets.QAction(MainWindow)
        self.action_triangle.setObjectName("action_triangle")
        self.action_full_screen = QtWidgets.QAction(MainWindow)
        self.action_full_screen.setObjectName("action_full_screen")
        self.action_show_as_window = QtWidgets.QAction(MainWindow)
        self.action_show_as_window.setObjectName("action_show_as_window")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_files_history = QtWidgets.QAction(MainWindow)
        self.action_files_history.setObjectName("action_files_history")
        self.menu.addAction(self.action_save)
        self.menu.addAction(self.action_open)
        self.menu.addAction(self.action_files_history)
        self.menu.addSeparator()
        self.menu.addAction(self.action_clear)
        self.menu.addSeparator()
        self.menu.addAction(self.action_quit)
        self.menu_2.addAction(self.action_full_screen)
        self.menu_2.addAction(self.action_show_as_window)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Вид"))
        self.tool_bar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_save.setText(_translate("MainWindow", "Сохранить"))
        self.action_open.setText(_translate("MainWindow", "Открыть"))
        self.action.setText(_translate("MainWindow", "Очистить"))
        self.action_clear.setText(_translate("MainWindow", "Очистить"))
        self.action_circle.setText(_translate("MainWindow", "Круг"))
        self.action_square.setText(_translate("MainWindow", "Квадрат"))
        self.action_triangle.setText(_translate("MainWindow", "Треугольник"))
        self.action_full_screen.setText(_translate("MainWindow", "Полный экран"))
        self.action_show_as_window.setText(_translate("MainWindow", "В окне"))
        self.action_quit.setText(_translate("MainWindow", "Выйти"))
        self.action_files_history.setText(_translate("MainWindow", "История"))
